version: '3.3'

networks:
  symfony:

services:
  app:
    build:
      context: ./.docker/nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: symfony_app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
      - db
    networks:
      - symfony

  php:
    build:
      context: ./.docker/php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    networks:
      - symfony

  db:
    image: mariadb:10.6
    container_name: symfony_db
    restart: unless-stopped
    tty: true
    volumes:
      - symfony_db:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: cristian
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - symfony

volumes:
  symfony_db:



